name: "01 Call Reusable Hello World"
on:
  workflow_dispatch: # This event triggers the workflow manually
jobs:
  say_call_reusable_hello_world_job:
    uses: ./.github/workflows/01_Reusable_Hello_World.yaml
